network:
  version: 2
  renderer: networkd

  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 10.20.2.10/24
      gateway4: 10.20.2.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 1.1.1.1