global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "dc-server"
    static_configs:
      - targets:
          - "10.10.1.10:9100"
        labels:
          server: "DC Server"
          location: "Data Center"

  - job_name: "drc-server"
    static_configs:
      - targets:
          - "10.10.1.20:9100"
        labels:
          server: "DRC Server"
          location: "Disaster Recovery Center"

  - job_name: "router"
    static_configs:
      - targets:
          - "10.10.1.2:9100"
        labels:
          server: "Router VM"
          role: "gateway"